site_name: view_drf
site_description: Test work vue js with django rest framework.
repo_url: https://github.com/lucky3337/view-drf
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/lucky3337">lucky3337</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
