# Generated by Django 2.1.9 on 2019-08-24 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(max_length=100)),
                ('mass', models.FloatField()),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('hair', models.CharField(choices=[('long', 'Long'), ('short', 'Short'), ('semi-long', 'Semi-long')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
